apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: server-pipeline-vikrambhat2 # executable ID, must be unique across your SAP AI Core instance, for example use `server-pipeline-yourname-1234`
  annotations:
    scenarios.ai.sap.com/description: "Learning to predict demand response"
    scenarios.ai.sap.com/name: "Demand Response on SAP"
    executables.ai.sap.com/description: "Create online server to make live predictions"
    executables.ai.sap.com/name: "model executable"
  labels:
    scenarios.ai.sap.com/id: "demand-datalines"
    ai.sap.com/version: "1.0"
spec:
  inputs:
    artifacts:
      - name: demandresponsemodel # placeholder name, do not add `-` in value use only alphanumeric chars
    parameters:
      - name: greetmessage # placeholder name
        type: string # required for every parameters
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency   # condition when to scale
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter # computing power
    spec: |
      predictor:
        imagePullSecrets:
          - name: dckr_pat_vW3IT-Xd_bZkvIhQJjZqOwXHNlI   # your docker registry secret
        minReplicas: 1
        maxReplicas: 5    # how much to scale
        containers:
        - name: kserve-container
          image: "docker.io/vikrambhat2/vb_model"
          ports:
            - containerPort: 3000    # customizable port
              protocol: TCP
          command: ["/bin/sh", "-c"]
          args:
          	- "python /app/src/main.py"
